host: khemenu.thoth-station.ninja
tls_verify: true
requirements_format: pipenv
overlays_dir: overlays

runtime_environments:
  - name: solver-fedora-34-py39
    operating_system:
      name: "fedora"
      version: "34"
    python_version: "3.9"
    recommendation_type: latest
    base_image: quay.io/thoth-station/s2i-thoth-f34-py39:v0.35.0

  - name: solver-fedora-35-py310
    operating_system:
      name: "fedora"
      version: "35"
    python_version: "3.10"
    recommendation_type: latest
    base_image: quay.io/thoth-station/s2i-thoth-f35-py310:v0.35.0

  - name: solver-rhel-8-py36
    operating_system:
      name: "rhel"
      version: "8"
    python_version: "3.6"
    recommendation_type: latest
    base_image: quay.io/thoth-station/s2i-thoth-ubi8-py36:v0.35.0

  - name: solver-rhel-8-py38
    operating_system:
      name: "rhel"
      version: "8"
    python_version: "3.8"
    recommendation_type: latest
    base_image: quay.io/thoth-station/s2i-thoth-ubi8-py38:v0.35.0

  - name: solver-rhel-9-py39
    operating_system:
      name: "rhel"
      version: "9"
    python_version: "3.9"
    recommendation_type: latest
    base_image: quay.io/thoth-station/s2i-thoth-ubi9-py39:v0.35.0

managers:
  - name: pipfile-requirements
  - name: update
    configuration:
      labels: [bot]
  - name: info
  - name: version
    configuration:
      assignees:
        - sesheta
      labels: [bot]
      changelog_file: true
