language: python
sudo: required
services:
- docker
python:
- '3.6'
script: true
env:
  matrix:
  - DOCKER_USER=fridex
  global:
    secure: YphlOnEIbJRZowhmSUXtT1CHzqBEs5lBt2qJQjgtL+eBtZGDKpVJzXzVR8YbzH3z/boLVTZPTzUkDhKy/hkx11Cn+3r/1Ucs4RAWQiWCV4ttdeuAujclGr6jxw4ExQqPcvPvKJLD/7nc7iV7pT2OO3of3VOLw08Ja/bakMP/Ch3wq/VaLPjULjzDuRrX/9JzEtV6v3c4vfFjc9ibtYPDMs9A9biz2o7tQ0xEMfzzjYiEyFzn0S+vm+YtYTYdbEM5PkE9ZOLpBfxcD6/EXUjoBTUzZNobL4CMd2SI9N3rh9ETBmwOe9IHnkl5aMVr0WwbQHtoGu+2SzsTY7QoCzV0Gs0i/iHIeTOm/NsIRpInjn9h3GmcOflcgXHzD80Muzpr0AgDpEq1S6O5KzGsWgCRc/EG7fV0tOVX3jtWjQbllF67fMvc1tBd+qFZpX5Ib4id2e8+WuQWzfY7PG03Q2gYuhI+3HkF1Y5wDJ4iHtpYYeaQFkLuJnAZko6q45xgea+X8aYSgcR5hMWN6u8PaSdIcI++4Hi39VI7Gush8HFQvVfobCfBSWeUJxM7LVZ0XrFOlsJoNC5kMGCSYjICJn4R0ggCqHgLH5q3h4kMmw6lj45XUhUPXpwLNFd/3v4xE9PR2pjchKL6uGgDW8HXrFnxF0wT4Q/PbewrxFByP07IgDA=
deploy:
  matrix:
  - provider: script
    script: bash build.sh
    password:
      secure: hi5QUsOn3WdqrrT4JzxKWj+5E/7ZPmoDwKJv0CxCrhBGhaJSXCP2goV3kFJMGzw6VpwZ7/6QXP6TXDREi5As+yCURXzfvZ73jUBc6nHSF2V70EGkSZ4IVGY4vmj/CU84IEOWO3iC8QF+MEgpq0LgD6XZO1wjru8iJ/mDa0GIhxjOGTJoPZDc9oaANl2L3iYHow1HNR4Mt1xUK8dsKJd4pf/NGh4WWFLkxvdmNPDL8oamDBxQ4exCH4TglxnTLDLA5hJ9yJ49FaWhixktKxPRaDigYUHzc+YQPRTRr66K5TWtoWhDAinkApVpFsIjupOlU/je1EhGqPGQq6E4TC77eyY80v8FwVUUVxiNPX7WmZilYKFvGy6q4zlx+JSl9lBzuYFOL/ce1mRjD56A0i4r2y7ZJKTu+OcThB9OzbyicCU21oE29TsFs9Ii+qRPGM80pFM+R/cQddTNrRincwTV3HnHGwNvgplvQhCKUf1zN3x6ljjkIfgBkgQysQuATqmTE7YvSCGi58v+kw4KRUtlWTn8P7OI8Zq6I7IN64YELfsaR6bVUTDF321cqxF1mg5QJLXGyYZQp6OrFpbm2nyEWEJ8cR0mt88PXF/5AM1iwAcis+i75U+jQ4ISL35kozIbkYSK381jnCZC4lzquxj+McejhGv5suOejYs0rgJEltc=
    on:
      branch: master
  - provider: pypi
    user: fridex
    on:
      tags: true
      branch: master
    distributions: sdist bdist_wheel
