- project:
    check:
      jobs:
        - thoth-coala
        - thoth-pytest
    gate:
      queue: thoth-station/core
      jobs:
        - thoth-coala
        - thoth-pytest
    release:
      jobs:
        - upload-pypi-sesheta
    post:
      jobs:
        - "trigger-build":
            vars:
              cluster: "paas.psi.redhat.com"
              namespace: "thoth-test-core"
              buildConfigName: "solver-fedora-29-py37"
        - "trigger-build":
            vars:
              cluster: "paas.psi.redhat.com"
              namespace: "thoth-test-core"
              buildConfigName: "solver-fedora-29-py36"
        - "trigger-build":
            vars:
              cluster: "paas.psi.redhat.com"
              namespace: "thoth-test-core"
              buildConfigName: "solver-fedora-28-py36"
        - "trigger-build":
            vars:
              cluster: "paas.psi.redhat.com"
              namespace: "thoth-test-core"
              buildConfigName: "solver-ubi-8-py36"
    kebechet-auto-gate:
      queue: thoth-station/core
      jobs:
        - thoth-coala
        - thoth-pytest
