apiVersion: v1
kind: Template
metadata:
  name: solver
  annotations:
    description: "Thoth: Solver Job Template"
    openshift.io/display-name: "Thoth: Solver"
    version: 0.2.0
    tags: thoth,ai-stacks,aistacks,solver,machinlearning
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This template defines resources needed to run solvers in Thoth, it is used
      to create new OpenShift Jobs running the analyzer.
    template.openshift.io/provider-display-name: "Red Hat, Inc."
  labels:
    template: solver
    app: thoth
    component: solver

parameters:
  - name: THOTH_SOLVER_WORKFLOW_ID
    description: "a UUID for the workflow instance"
    displayName: "Workflow UUID"
    required: true
  - name: THOTH_SOLVER_NAME
    description: "Name of the solver to be used, for example: solver-rhel-8.0-py37"
    displayName: "Solver Name"
    required: true
  - name: THOTH_SOLVER_PACKAGES
    description: "Packages to be resolved"
    displayName: "Packages to be analyzed by solver"
    required: true
  - name: THOTH_SOLVER_NO_TRANSITIVE
    description: "Do not resolve transitive dependencies"
    displayName: "No transitive dependencies"
    required: true
  - name: THOTH_SOLVER_INDEXES
    description: "A comma separated list of indexes to scan during solver run"
    displayName: "Python Package Indexes"
    value: ""
  - name: THOTH_FORCE_SYNC
    description: Perform force sync - sync data even if they are reported to be existing
    displayName: Perform force sync
    required: true
    value: "0"
  - name: THOTH_LOG_SOLVER
    description: "Log solver actions"
    displayName: "Log solver actions"
    required: true
    value: INFO

  - description: Registry the ImageStream to be use lives in
    displayName: ImageStream Registry
    required: true
    name: IMAGE_STREAM_REGISTRY
    value: "docker-registry.default.svc:5000"
  - description: Namespace the ImageStream to be use lives in
    displayName: ImageStream Project
    required: true
    name: IMAGE_STREAM_NAMESPACE
    value: "thoth-infra-stage"
  - description: Tag of the ImageStream to be use
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: "latest"

objects:
  - apiVersion: argoproj.io/v1alpha1
    kind: Workflow
    metadata:
      generateName: "solver${THOTH_SOLVER_WORKFLOW_ID}"
      annotations:
        thoth-station.ninja/template-version: 0.2.0
      labels:
        app: thoth
        component: solver
    spec:
      serviceAccountName: argo
      podGC:
        strategy: OnWorkflowSuccess
      entrypoint: solve-and-sync
      arguments:
        parameters:
          - name: "THOTH_SOLVER_NAME"
            value: "${THOTH_SOLVER_NAME}"
          - name: "THOTH_SOLVER_WORKFLOW_ID"
            value: "${THOTH_SOLVER_WORKFLOW_ID}"
          - name: "THOTH_LOG_SOLVER"
            value: "${THOTH_LOG_SOLVER}"
          - name: "THOTH_SOLVER_NO_TRANSITIVE"
            value: "${THOTH_SOLVER_NO_TRANSITIVE}"
          - name: "THOTH_SOLVER_PACKAGES"
            value: "${THOTH_SOLVER_PACKAGES}"
          - name: "THOTH_SOLVER_INDEXES"
            value: "${THOTH_SOLVER_INDEXES}"
          - name: "THOTH_FORCE_SYNC"
            value: "${THOTH_FORCE_SYNC}"
      volumes:
        - name: workdir
          emptyDir: {}
        - name: output
          emptyDir: {}
      templates:
        - name: "solve-and-sync"
          archiveLocation:
            archiveLogs: true
          dag:
            tasks:
              - name: "solverany"
                templateRef:
                  name: "solver-any"
                  template: "solve"
                arguments:
                  parameters:
                    - name: "THOTH_SOLVER_NAME"
                      value: "{{workflow.parameters.THOTH_SOLVER_NAME}}"
                    - name: "THOTH_SOLVER_DOCUMENT_ID"
                      value: "{{workflow.parameters.THOTH_SOLVER_NAME}}-{{workflow.parameters.THOTH_SOLVER_WORKFLOW_ID}}"
                    - name: "THOTH_LOG_SOLVER"
                      value: "{{workflow.parameters.THOTH_LOG_SOLVER}}"
                    - name: "THOTH_SOLVER_NO_TRANSITIVE"
                      value: "{{workflow.parameters.THOTH_SOLVER_NO_TRANSITIVE}}"
                    - name: "THOTH_SOLVER_PACKAGES"
                      value: "{{workflow.parameters.THOTH_SOLVER_PACKAGES}}"
                    - name: "THOTH_SOLVER_INDEXES"
                      value: "{{workflow.parameters.THOTH_SOLVER_INDEXES}}"

              - name: "graph-sync-solverany"
                dependencies:
                  - "solverany"
                templateRef:
                  name: "graph-sync"
                  template: "graph-sync"
                arguments:
                  artifacts:
                    - name: outputdocument
                      from: "{{tasks.solverany.outputs.artifacts.outputdocument}}"
                  parameters:
                    - name: "THOTH_DOCUMENT_ID"
                      value: "{{workflow.parameters.THOTH_SOLVER_NAME}}-{{workflow.parameters.THOTH_SOLVER_WORKFLOW_ID}}"
                    - name: "THOTH_FORCE_SYNC"
                      value: "{{workflow.parameters.THOTH_FORCE_SYNC}}"

  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: "${THOTH_SOLVER_JOB_ID}"
      annotations:
        thoth-station.ninja/template-version: 0.2.0
      labels:
        app: thoth
        component: solver
        solver-type: solver-rhel-8-py36
        operator: graph-sync
        task: solver
        mark: cleanup
    spec:
      template:
        metadata:
          labels:
            app: thoth
            component: solver
            solver-type: solver-rhel-8-py36
            task: solver
            mark: cleanup
            ttl: "2h"
        spec:
          restartPolicy: OnFailure
          containers:
            - name: solver
              env:
                - name: THOTH_SOLVER
                  value: solver-rhel-8-py36
                - name: THOTH_DOCUMENT_ID
                  value: "${THOTH_DOCUMENT_ID}"
                - name: THOTH_LOG_SOLVER
                  value: "${THOTH_LOG_SOLVER}"
                - name: THOTH_SOLVER_NO_TRANSITIVE
                  value: "${THOTH_SOLVER_NO_TRANSITIVE}"
                - name: THOTH_SOLVER_PACKAGES
                  value: "${THOTH_SOLVER_PACKAGES}"
                - name: THOTH_SOLVER_OUTPUT
                  value: "${THOTH_SOLVER_OUTPUT}"
                - name: THOTH_SOLVER_INDEXES
                  value: "${THOTH_SOLVER_INDEXES}"
                - name: THOTH_SOLVER_VIRTUALENV
                  value: "/home/solver/venv"
                - name: THOTH_DEPLOYMENT_NAME
                  valueFrom:
                    configMapKeyRef:
                      key: storage-bucket-name
                      name: thoth
                - name: SENTRY_DSN
                  valueFrom:
                    secretKeyRef:
                      name: thoth
                      key: sentry-dsn
              image: "${IMAGE_STREAM_REGISTRY}/${IMAGE_STREAM_NAMESPACE}/solver-rhel-8-py36:${IMAGE_STREAM_TAG}"
              livenessProbe:
                failureThreshold: 1
                initialDelaySeconds: 900
                periodSeconds: 10
                tcpSocket:
                  port: 80
              resources:
                limits:
                  cpu: 1
                  memory: 2Gi
                requests:
                  cpu: 1
                  memory: 2Gi

  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: "${THOTH_SOLVER_JOB_ID}"
      annotations:
        thoth-station.ninja/template-version: 0.2.0
      labels:
        app: thoth
        component: solver
        solver-type: solver-fedora-31-py38
        operator: graph-sync
        task: solver
        mark: cleanup
    spec:
      template:
        metadata:
          labels:
            app: thoth
            component: solver
            solver-type: solver-fedora-31-py38
            mark: cleanup
            task: solver
            ttl: 2h
        spec:
          restartPolicy: OnFailure
          containers:
            - name: solver
              env:
                - name: THOTH_SOLVER
                  value: solver-fedora-31-py38
                - name: THOTH_DOCUMENT_ID
                  value: "${THOTH_DOCUMENT_ID}"
                - name: THOTH_LOG_SOLVER
                  value: "${THOTH_LOG_SOLVER}"
                - name: THOTH_SOLVER_NO_TRANSITIVE
                  value: "${THOTH_SOLVER_NO_TRANSITIVE}"
                - name: THOTH_SOLVER_PACKAGES
                  value: "${THOTH_SOLVER_PACKAGES}"
                - name: THOTH_SOLVER_OUTPUT
                  value: "${THOTH_SOLVER_OUTPUT}"
                - name: THOTH_SOLVER_INDEXES
                  value: "${THOTH_SOLVER_INDEXES}"
                - name: THOTH_SOLVER_VIRTUALENV
                  value: "/home/solver/venv"
                - name: THOTH_DEPLOYMENT_NAME
                  valueFrom:
                    configMapKeyRef:
                      key: storage-bucket-name
                      name: thoth
                - name: SENTRY_DSN
                  valueFrom:
                    secretKeyRef:
                      name: thoth
                      key: sentry-dsn
              image: "${IMAGE_STREAM_REGISTRY}/${IMAGE_STREAM_NAMESPACE}/solver-fedora-31-py38:${IMAGE_STREAM_TAG}"
              livenessProbe:
                failureThreshold: 1
                initialDelaySeconds: 900
                periodSeconds: 10
                tcpSocket:
                  port: 80
              resources:
                limits:
                  cpu: 1
                  memory: 2Gi
                requests:
                  cpu: 1
                  memory: 2Gi

  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: "${THOTH_SOLVER_JOB_ID}"
      annotations:
        thoth-station.ninja/template-version: 0.2.0
      labels:
        app: thoth
        component: solver
        solver-type: solver-fedora-31-py37
        operator: graph-sync
        task: solver
        mark: cleanup
    spec:
      template:
        metadata:
          labels:
            app: thoth
            component: solver
            solver-type: solver-fedora-31-py37
            mark: cleanup
            task: solver
            ttl: 2h
        spec:
          restartPolicy: OnFailure
          containers:
            - name: solver
              env:
                - name: THOTH_SOLVER
                  value: solver-fedora-31-py37
                - name: THOTH_DOCUMENT_ID
                  value: "${THOTH_DOCUMENT_ID}"
                - name: THOTH_LOG_SOLVER
                  value: "${THOTH_LOG_SOLVER}"
                - name: THOTH_SOLVER_NO_TRANSITIVE
                  value: "${THOTH_SOLVER_NO_TRANSITIVE}"
                - name: THOTH_SOLVER_PACKAGES
                  value: "${THOTH_SOLVER_PACKAGES}"
                - name: THOTH_SOLVER_OUTPUT
                  value: "${THOTH_SOLVER_OUTPUT}"
                - name: THOTH_SOLVER_INDEXES
                  value: "${THOTH_SOLVER_INDEXES}"
                - name: THOTH_SOLVER_VIRTUALENV
                  value: "/home/solver/venv"
                - name: THOTH_DEPLOYMENT_NAME
                  valueFrom:
                    configMapKeyRef:
                      key: storage-bucket-name
                      name: thoth
                - name: SENTRY_DSN
                  valueFrom:
                    secretKeyRef:
                      name: thoth
                      key: sentry-dsn
              image: "${IMAGE_STREAM_REGISTRY}/${IMAGE_STREAM_NAMESPACE}/solver-fedora-31-py37:${IMAGE_STREAM_TAG}"
              livenessProbe:
                failureThreshold: 1
                initialDelaySeconds: 900
                periodSeconds: 10
                tcpSocket:
                  port: 80
              resources:
                limits:
                  cpu: 1
                  memory: 2Gi
                requests:
                  cpu: 1
                  memory: 2Gi
